setGeneric("summary", function(object) standardGeneric("summary"))
setGeneric("PretrainLearningRate", function(object) standardGeneric("PretrainLearningRate"))
setGeneric("LearningRate", function(object) standardGeneric("LearningRate"))
setGeneric("CorruptionLevel", function(object) standardGeneric("CorruptionLevel"))
setGeneric("TrainingEpochs", function(object) standardGeneric("TrainingEpochs"))
setGeneric("HiddenRepresentation", function(object) standardGeneric("HiddenRepresentation"))
setGeneric("PretrainingEpochs", function(object) standardGeneric("PretrainingEpochs"))
setGeneric("FinetuneLearningRate", function(object) standardGeneric("FinetuneLearningRate"))
setGeneric("Step", function(object) standardGeneric("Step"))
setGeneric("FinetuneEpochs", function(object) standardGeneric("FinetuneEpochs"))
setGeneric("pretrain", function(object) standardGeneric("pretrain"))
setGeneric("train", function(object) standardGeneric("train"))
setGeneric("finetune", function(object) standardGeneric("finetune"))
setGeneric("predict", function(object, test) standardGeneric("predict"))
setGeneric("reconstruct", function(object, test) standardGeneric("reconstruct"))
setGeneric("setPretrainLearningRate", function(object, plr) standardGeneric("setPretrainLearningRate"))
setGeneric("setStep", function(object, s) standardGeneric("setStep"))
setGeneric("setPretrainEpochs", function(object, pe) standardGeneric("setPretrainEpochs"))
setGeneric("setFinetuneEpochs", function(object, fe) standardGeneric("setFinetuneEpochs"))
setGeneric("setFinetuneLearningRate", function(object, flr) standardGeneric("setFinetuneLearningRate"))
setGeneric("setLearningRate", function(object, lr) standardGeneric("setLearningRate"))
setGeneric("setCorruptionLevel", function(object, cl) standardGeneric("setCorruptionLevel"))
setGeneric("setTrainingEpochs", function(object, te) standardGeneric("setTrainingEpochs"))
setGeneric("setHiddenRepresentation", function(object, h) standardGeneric("setHiddenRepresentation"))

